name = "JutulModelConfigurations"
uuid = "da9e779f-cf6d-4bf6-baf7-0ed062534939"
authors = ["Grant Bruer gbruer15@gmail.com and contributors"]
version = "1.0.0-DEV"

[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"

[extensions]
JutulDarcyExt = "JutulDarcy"

[compat]
Configurations = "0.17"
JutulDarcy = "0.2.26"
PackageExtensionCompat = "1"
julia = "1.8"

[extras]
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
